server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
         include: "*"

spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/zipkin/


logging:
  file:
    path: C:\Users\USER\Downloads\logs\microservice.logs